### ISSUE TITLE
Power of the Archdruid & Innervate

### ISSUE THREAD

**Issue by talizea** [asvanberg/druid-legendary-analyser#5]
It would be cool to see how much healing was caused by [Power of the Archdruid](http://www.wowhead.com/spell=189877/power-of-the-archdruid) and how much mana was saved from spells cast during [Innervate](http://www.wowhead.com/spell=29166/innervate) ;)

**Comment by asvanberg** [comment]
Both of these are available in the [WoW Analyzer](https://wowanalyzer.com/) so there is not much point to add them. At least the innervate module is very good, the PotA one is probably an approximation based on your average rejuvenation/regrowth but that should be accurate enough.
